# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

default:
  image: maven

stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - coverage
  - quality

validate: # This job runs in the build stage, which runs first.
  stage: build
  script: cd passwordManager && mvn validate
  allow_failure: false
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"

compile:
  stage: build
  script: cd passwordManager && mvn compile
  allow_failure: false
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
  artifacts:
    paths:
      - passwordManager/core/target/classes/*
      - passwordManager/localpersistence/target/classes/*
      - passwordManager/ui/target/classes/*
    expire_in: 10 minutes

test:
  stage: test
  needs: ["compile"]
  script: cd passwordManager && mvn test
  allow_failure: false
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
  artifacts:
    paths:
      - passwordManager/core/target/surefire-reports/*.xml
      - passwordManager/localpersistance/target/surefire-reports/*.xml
      - passwordManager/ui/target/surefire-reports/*.xml
    reports:
      junit:
        - passwordManager/core/target/surefire-reports/*.xml
        - passwordManager/core/target/surefire-reports/*.xml
        - passwordManager/core/target/surefire-reports/*.xml

test-coverage-minimum:
  stage: coverage
  needs: ["test"]
  script: cd passwordManager && mvn verify
  allow_failure: false
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"

test-coverage-80:
  stage: coverage
  needs: ["test"]
  script: cd passwordManager && mvn verify -Dminimum=0.8
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"

checkstyle:
  stage: quality
  needs: ["compile"]
  script: cd passwordManager && mvn checkstyle:check
  allow_failure: true
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
